export default {
    NUMERO_INTEIRO: 'NUMERO_INTEIRO',
    NUMERO_REAL: 'NUMERO_REAL',
    CARACTERE: 'CARACTERE',
    STRING: 'STRING',
    ATRIBUICAO: 'ATRIBUICAO',
    CONSTANTE_CARACTERE: 'CONSTANTE_CARACTERE',
    CONSTANTE_STRING: 'CONSTANTE_STRING',
    OPERADOR_RELACIONAL: 'OPERADOR_RELACIONAL',
    OPERADOR_LOGICO: 'OPERADOR_LOGICO',
    OPERADOR_ARITMETICO: 'OPERADOR_ARITMETICO',
    SIMBOLO_ESPECIAL: 'SIMBOLO_ESPECIAL',
    COMANDO_DE_ENTRADA: 'COMANDO_DE_ENTRADA',
    COMANDO_DE_SAIDA: 'COMANDO_DE_SAIDA',
    PALAVRA_RESERVADA: 'PALAVRA_RESERVADA'
}